"""Initial migration: user, oauth, campaign, report, keyword tables

Revision ID: 347b84237c87
Revises: 5785681901d3
Create Date: 2026-02-01 19:15:57.745228

"""


# revision identifiers, used by Alembic.
revision = '347b84237c87'
down_revision = '5785681901d3'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
