"""Add conversation models and campaign_ids column

Revision ID: 3de4ed13f3f8
Revises: 347b84237c87
Create Date: 2026-02-02 01:21:32.845803

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3de4ed13f3f8'
down_revision = '347b84237c87'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('report_schedules', sa.Column('campaign_ids', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('report_schedules', 'campaign_ids')
    # ### end Alembic commands ###
