"""Initial schema

Revision ID: 5785681901d3
Revises: 
Create Date: 2026-02-01 04:44:04.869412

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5785681901d3'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workspace_id', sa.String(length=50), nullable=False),
    sa.Column('workspace_name', sa.String(length=255), nullable=False),
    sa.Column('bot_token', sa.String(length=255), nullable=True),
    sa.Column('slack_channel_id', sa.String(length=50), nullable=True),
    sa.Column('installed_at', sa.DateTime(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('settings', sa.JSON(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_tenants_workspace_id'), 'tenants', ['workspace_id'], unique=True)
    op.create_table('google_ads_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('account_name', sa.String(length=255), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('timezone', sa.String(length=50), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_google_ads_accounts_customer_id'), 'google_ads_accounts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_google_ads_accounts_tenant_id'), 'google_ads_accounts', ['tenant_id'], unique=False)
    op.create_table('keyword_candidates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.String(length=50), nullable=False),
    sa.Column('campaign_name', sa.String(length=255), nullable=False),
    sa.Column('search_term', sa.String(length=255), nullable=False),
    sa.Column('cost', sa.Float(), nullable=False),
    sa.Column('clicks', sa.Integer(), nullable=False),
    sa.Column('conversions', sa.Integer(), nullable=False),
    sa.Column('detected_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'EXPIRED', name='keywordstatus'), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_keyword_candidates_detected_at'), 'keyword_candidates', ['detected_at'], unique=False)
    op.create_index(op.f('ix_keyword_candidates_tenant_id'), 'keyword_candidates', ['tenant_id'], unique=False)
    op.create_table('oauth_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('provider', sa.Enum('GOOGLE', 'SLACK', name='oauthprovider'), nullable=False),
    sa.Column('access_token', sa.String(), nullable=False),
    sa.Column('refresh_token', sa.String(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.Column('scope', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_oauth_tokens_tenant_id'), 'oauth_tokens', ['tenant_id'], unique=False)
    op.create_table('performance_thresholds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('min_cost_for_detection', sa.Float(), nullable=False),
    sa.Column('min_clicks_for_detection', sa.Integer(), nullable=False),
    sa.Column('lookback_days', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_thresholds_tenant_id'), 'performance_thresholds', ['tenant_id'], unique=True)
    op.create_table('report_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('report_type', sa.String(length=50), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('slack_message_ts', sa.String(length=50), nullable=True),
    sa.Column('gemini_insight', sa.String(), nullable=True),
    sa.Column('metrics', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_history_tenant_id'), 'report_history', ['tenant_id'], unique=False)
    op.create_table('report_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('frequency', sa.Enum('DAILY', 'WEEKLY', 'MONTHLY', 'DISABLED', name='reportfrequency'), nullable=False),
    sa.Column('day_of_week', sa.Integer(), nullable=True),
    sa.Column('day_of_month', sa.Integer(), nullable=True),
    sa.Column('time_of_day', sa.Time(), nullable=False),
    sa.Column('timezone', sa.String(length=50), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_report_schedules_tenant_id'), 'report_schedules', ['tenant_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('slack_user_id', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('last_login', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_slack_user_id'), 'users', ['slack_user_id'], unique=False)
    op.create_index(op.f('ix_users_tenant_id'), 'users', ['tenant_id'], unique=False)
    op.create_table('approval_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('keyword_candidate_id', sa.Integer(), nullable=False),
    sa.Column('slack_message_ts', sa.String(length=50), nullable=False),
    sa.Column('requested_at', sa.DateTime(), nullable=False),
    sa.Column('responded_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('action', sa.Enum('APPROVE', 'IGNORE', 'EXPIRED', name='approvalaction'), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['keyword_candidate_id'], ['keyword_candidates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_approval_requests_expires_at'), 'approval_requests', ['expires_at'], unique=False)
    op.create_index(op.f('ix_approval_requests_keyword_candidate_id'), 'approval_requests', ['keyword_candidate_id'], unique=True)
    op.create_index(op.f('ix_approval_requests_slack_message_ts'), 'approval_requests', ['slack_message_ts'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_approval_requests_slack_message_ts'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_keyword_candidate_id'), table_name='approval_requests')
    op.drop_index(op.f('ix_approval_requests_expires_at'), table_name='approval_requests')
    op.drop_table('approval_requests')
    op.drop_index(op.f('ix_users_tenant_id'), table_name='users')
    op.drop_index(op.f('ix_users_slack_user_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_report_schedules_tenant_id'), table_name='report_schedules')
    op.drop_table('report_schedules')
    op.drop_index(op.f('ix_report_history_tenant_id'), table_name='report_history')
    op.drop_table('report_history')
    op.drop_index(op.f('ix_performance_thresholds_tenant_id'), table_name='performance_thresholds')
    op.drop_table('performance_thresholds')
    op.drop_index(op.f('ix_oauth_tokens_tenant_id'), table_name='oauth_tokens')
    op.drop_table('oauth_tokens')
    op.drop_index(op.f('ix_keyword_candidates_tenant_id'), table_name='keyword_candidates')
    op.drop_index(op.f('ix_keyword_candidates_detected_at'), table_name='keyword_candidates')
    op.drop_table('keyword_candidates')
    op.drop_index(op.f('ix_google_ads_accounts_tenant_id'), table_name='google_ads_accounts')
    op.drop_index(op.f('ix_google_ads_accounts_customer_id'), table_name='google_ads_accounts')
    op.drop_table('google_ads_accounts')
    op.drop_index(op.f('ix_tenants_workspace_id'), table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
